using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("AlicizaX.Framework.Editor")]
[assembly: InternalsVisibleTo("AlicizaX.Framework.Resources.Tests")]
[assembly: InternalsVisibleTo("AlicizaX.Framework.Resources.Editor.Tests")]
[assembly: InternalsVisibleTo("AlicizaX.Debugger")]
[assembly: InternalsVisibleTo("AlicizaX.Framework.MemoryPool.Tests")]
[assembly: InternalsVisibleTo("AlicizaX.Framework.MemoryPool.Editor.Tests")]
[assembly: InternalsVisibleTo("AlicizaX.Framework.Audio.Tests")]
[assembly: InternalsVisibleTo("AlicizaX.Framework.Audio.Editor.Tests")]
[assembly: InternalsVisibleTo("AlicizaX.Framework.Timer.Tests")]
[assembly: InternalsVisibleTo("AlicizaX.Framework.Timer.Editor.Tests")]
[assembly: InternalsVisibleTo("AlicizaX.Framework.ObjectPool.Tests")]
[assembly: InternalsVisibleTo("AlicizaX.Framework.ObjectPool.Editor.Tests")]
[assembly: InternalsVisibleTo("AlicizaX.Framework.GameObjectPool.Tests")]
[assembly: InternalsVisibleTo("AlicizaX.Framework.GameObjectPool.Editor.Tests")]
[assembly: InternalsVisibleTo("AlicizaX.Framework.UI.Tests")]
[assembly: InternalsVisibleTo("AlicizaX.Framework.UI.Editor.Tests")]

[assembly: InternalsVisibleTo("AlicizaX.Framework.Event.Tests")]
[assembly: InternalsVisibleTo("AlicizaX.Framework.Event.Editor.Tests")]
